name: Build & Deploy Eleventy Site

# Trigger on pushes to main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the Eleventy site
      - name: Build site with Eleventy
        run: npm run build

      # 5. Deploy to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
