name: Build & Deploy Eleventy Site

# Trigger on pushes to main
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-deploy:
    name: Build and Deploy Eleventy Site
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}